[xdebug]
xdebug.start_with_request=yes
xdebug.mode=debug,coverage
zend_extension=xdebug.so
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=VSCODE
xdebug.log_level=0 ; Supresses warnings when Xdebug is not running

[php]
session.use_cookies = 0
expose_php = off
log_errors=1
error_log="/var/task/error.log"
error_reporting = E_ALL
